spring:
  application.name: CI

  datasource:
    type: mysql
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ci
    username: root
    password: admin

  jpa:
     show-sql: true